# Generated by Django 5.0.1 on 2024-02-29 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_file',
            field=models.FileField(null=True, upload_to='product_files'),
        ),
    ]
