# Generated by Django 5.0.1 on 2024-03-02 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_product_product_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='downlaods',
            field=models.CharField(default=0, max_length=200, null=True),
        ),
    ]
