# Generated by Django 5.0.1 on 2024-03-02 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_product_downlaods'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='downlaods',
            new_name='downloads',
        ),
    ]
