# Generated by Django 5.0.1 on 2024-03-02 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_rename_downlaods_product_downloads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='downloads',
            field=models.IntegerField(default=0),
        ),
    ]
