# Generated by Django 5.0.1 on 2024-03-04 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_wishlist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishlist',
            options={'verbose_name_plural': 'Wish List'},
        ),
    ]
