# Generated by Django 5.0.1 on 2024-03-04 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_customer_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='image',
            new_name='customer_image',
        ),
    ]
