# Generated by Django 5.0.1 on 2024-03-06 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_rename_image_customer_customer_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAddres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('default_address', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customeraddres', to='main.customer')),
            ],
        ),
        migrations.DeleteModel(
            name='CustomerAddress',
        ),
    ]
