# Generated by Django 5.0.1 on 2024-03-07 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_alter_customeraddress_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='customer_image',
            field=models.ImageField(null=True, upload_to='seller_images/'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='mobile',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
