# Generated by Django 5.0.1 on 2024-03-09 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_alter_vendor_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='published_status',
            field=models.BooleanField(default=False),
        ),
    ]
