# Generated by Django 5.0.1 on 2024-03-20 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_rename_ratings_productrating_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='cat_img',
            field=models.FileField(null=True, upload_to='category_imgs/'),
        ),
    ]
